# Generated by Django 5.1.1 on 2024-10-13 11:19

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doska_ob", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="categories", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
